stages:
  - run
  - build
  - doc
before_script:
  - python -V
  - pip -V

py27:
  stage: run
  image: thebjorn/dktestpackage2:latest
  script:
    - dk testpackage --ci
  allow_failure: true
  artifacts:
    paths:
      - build/*

py3:
  stage: run
  image: thebjorn/dktestpackage3:latest
  script:
    - dk testpackage --ci
  allow_failure: true
  artifacts:
    paths:
      - build/*

coverage:
  stage: build
  image: thebjorn/dktestpackage2:latest
  script:
    - dk combine-coverage
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  dependencies:
    - py27
    - py3
  artifacts:
    paths:
      - build/coverage/*

wheel:
  stage: build
  image: thebjorn/dktestpackage2:latest
  script:
    - dk build-wheel
  dependencies:
    - py27
  artifacts:
    paths:
      - docs/badge-wheel.rst

pages:
  stage: doc
  image: thebjorn/dktestpackage2:latest
  script:
    - dk build-docs
  dependencies:
    - coverage
    - wheel
  artifacts:
    paths:
      - public
  only:
    - master
